window.esdocSearchIndex = [
  [
    "./nawi/widgets/layout/hlayout/hlayout.js~hlayout",
    "class/nawi/widgets/layout/hlayout/HLayout.js~HLayout.html",
    "<span>HLayout</span> <span class=\"search-result-import-path\">./nawi/widgets/layout/hlayout/HLayout.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/layout/hlayout/hlayoutproto.js~hlayoutproto",
    "class/nawi/widgets/layout/hlayout/HLayoutProto.js~HLayoutProto.html",
    "<span>HLayoutProto</span> <span class=\"search-result-import-path\">./nawi/widgets/layout/hlayout/HLayoutProto.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/layout/hlayout/hlayoutstyle.js~hlayoutstyle",
    "class/nawi/widgets/layout/hlayout/HLayoutStyle.js~HLayoutStyle.html",
    "<span>HLayoutStyle</span> <span class=\"search-result-import-path\">./nawi/widgets/layout/hlayout/HLayoutStyle.js</span>",
    "class"
  ],
  [
    "./nawi/core/tools/kernel.js~kernel",
    "class/nawi/core/tools/Kernel.js~Kernel.html",
    "<span>Kernel</span> <span class=\"search-result-import-path\">./nawi/core/tools/Kernel.js</span>",
    "class"
  ],
  [
    "./nawi/core/tools/nmap.js~nmap",
    "class/nawi/core/tools/NMap.js~NMap.html",
    "<span>NMap</span> <span class=\"search-result-import-path\">./nawi/core/tools/NMap.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/widget/stylecontainer.js~stylecontainer",
    "class/nawi/widgets/widget/StyleContainer.js~StyleContainer.html",
    "<span>StyleContainer</span> <span class=\"search-result-import-path\">./nawi/widgets/widget/StyleContainer.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/view/tabview/tabview.js~tabview",
    "class/nawi/widgets/view/tabview/TabView.js~TabView.html",
    "<span>TabView</span> <span class=\"search-result-import-path\">./nawi/widgets/view/tabview/TabView.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/view/tabview/tabviewproto.js~tabviewproto",
    "class/nawi/widgets/view/tabview/TabViewProto.js~TabViewProto.html",
    "<span>TabViewProto</span> <span class=\"search-result-import-path\">./nawi/widgets/view/tabview/TabViewProto.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/view/tabview/tabviewstyle.js~tabviewstyle",
    "class/nawi/widgets/view/tabview/TabViewStyle.js~TabViewStyle.html",
    "<span>TabViewStyle</span> <span class=\"search-result-import-path\">./nawi/widgets/view/tabview/TabViewStyle.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/widget/widget.js~widget",
    "class/nawi/widgets/widget/Widget.js~Widget.html",
    "<span>Widget</span> <span class=\"search-result-import-path\">./nawi/widgets/widget/Widget.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/widget/widgetproto.js~widgetproto",
    "class/nawi/widgets/widget/WidgetProto.js~WidgetProto.html",
    "<span>WidgetProto</span> <span class=\"search-result-import-path\">./nawi/widgets/widget/WidgetProto.js</span>",
    "class"
  ],
  [
    "./nawi/widgets/widget/widgetstyle.js~widgetstyle",
    "class/nawi/widgets/widget/WidgetStyle.js~WidgetStyle.html",
    "<span>WidgetStyle</span> <span class=\"search-result-import-path\">./nawi/widgets/widget/WidgetStyle.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "nawi/core/tools/kernel.js",
    "file/nawi/core/tools/Kernel.js.html",
    "nawi/core/tools/Kernel.js",
    "file"
  ],
  [
    "nawi/core/tools/kernel.js~kernel#constructor",
    "class/nawi/core/tools/Kernel.js~Kernel.html#instance-constructor-constructor",
    "nawi/core/tools/Kernel.js~Kernel#constructor",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.accessor",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-accessor",
    "nawi/core/tools/Kernel.js~Kernel.accessor",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.attachclass",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-attachClass",
    "nawi/core/tools/Kernel.js~Kernel.attachClass",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.constant",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-constant",
    "nawi/core/tools/Kernel.js~Kernel.constant",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.copyarray",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-copyArray",
    "nawi/core/tools/Kernel.js~Kernel.copyArray",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.copyobject",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-copyObject",
    "nawi/core/tools/Kernel.js~Kernel.copyObject",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.extend",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-extend",
    "nawi/core/tools/Kernel.js~Kernel.extend",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.hidden",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-hidden",
    "nawi/core/tools/Kernel.js~Kernel.hidden",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.invisible",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-invisible",
    "nawi/core/tools/Kernel.js~Kernel.invisible",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isarray",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isArray",
    "nawi/core/tools/Kernel.js~Kernel.isArray",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isboolean",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isBoolean",
    "nawi/core/tools/Kernel.js~Kernel.isBoolean",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isfunction",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isFunction",
    "nawi/core/tools/Kernel.js~Kernel.isFunction",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isnull",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isNull",
    "nawi/core/tools/Kernel.js~Kernel.isNull",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isnumber",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isNumber",
    "nawi/core/tools/Kernel.js~Kernel.isNumber",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isobject",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isObject",
    "nawi/core/tools/Kernel.js~Kernel.isObject",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isreadytoes6",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isReadyToES6",
    "nawi/core/tools/Kernel.js~Kernel.isReadyToES6",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isstring",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isString",
    "nawi/core/tools/Kernel.js~Kernel.isString",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.isundefined",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-isUndefined",
    "nawi/core/tools/Kernel.js~Kernel.isUndefined",
    "method"
  ],
  [
    "nawi/core/tools/kernel.js~kernel.makeparametersarray",
    "class/nawi/core/tools/Kernel.js~Kernel.html#static-method-makeParametersArray",
    "nawi/core/tools/Kernel.js~Kernel.makeParametersArray",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js",
    "file/nawi/core/tools/NMap.js.html",
    "nawi/core/tools/NMap.js",
    "file"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#clear",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-clear",
    "nawi/core/tools/NMap.js~NMap#clear",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#constructor",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-constructor-constructor",
    "nawi/core/tools/NMap.js~NMap#constructor",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#delete",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-delete",
    "nawi/core/tools/NMap.js~NMap#delete",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#entries",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-entries",
    "nawi/core/tools/NMap.js~NMap#entries",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#firstkey",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-firstKey",
    "nawi/core/tools/NMap.js~NMap#firstKey",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#firstvalue",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-firstValue",
    "nawi/core/tools/NMap.js~NMap#firstValue",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#foreach",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-forEach",
    "nawi/core/tools/NMap.js~NMap#forEach",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#get",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-get",
    "nawi/core/tools/NMap.js~NMap#get",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#has",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-has",
    "nawi/core/tools/NMap.js~NMap#has",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#indexedkey",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-indexedKey",
    "nawi/core/tools/NMap.js~NMap#indexedKey",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#indexedvalue",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-indexedValue",
    "nawi/core/tools/NMap.js~NMap#indexedValue",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#iterable",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-get-iterable",
    "nawi/core/tools/NMap.js~NMap#iterable",
    "member"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#keys",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-keys",
    "nawi/core/tools/NMap.js~NMap#keys",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#lastkey",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-lastKey",
    "nawi/core/tools/NMap.js~NMap#lastKey",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#lastvalue",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-lastValue",
    "nawi/core/tools/NMap.js~NMap#lastValue",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#set",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-set",
    "nawi/core/tools/NMap.js~NMap#set",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#size",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-get-size",
    "nawi/core/tools/NMap.js~NMap#size",
    "member"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#valueof",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-valueOf",
    "nawi/core/tools/NMap.js~NMap#valueOf",
    "method"
  ],
  [
    "nawi/core/tools/nmap.js~nmap#values",
    "class/nawi/core/tools/NMap.js~NMap.html#instance-method-values",
    "nawi/core/tools/NMap.js~NMap#values",
    "method"
  ],
  [
    "nawi/libnawi.js",
    "file/nawi/libnawi.js.html",
    "nawi/libnawi.js",
    "file"
  ],
  [
    "nawi/widgets/layout/hlayout/hlayout.js",
    "file/nawi/widgets/layout/hlayout/HLayout.js.html",
    "nawi/widgets/layout/hlayout/HLayout.js",
    "file"
  ],
  [
    "nawi/widgets/layout/hlayout/hlayout.js~hlayout#constructor",
    "class/nawi/widgets/layout/hlayout/HLayout.js~HLayout.html#instance-constructor-constructor",
    "nawi/widgets/layout/hlayout/HLayout.js~HLayout#constructor",
    "method"
  ],
  [
    "nawi/widgets/layout/hlayout/hlayout.js~hlayout.create",
    "class/nawi/widgets/layout/hlayout/HLayout.js~HLayout.html#static-method-create",
    "nawi/widgets/layout/hlayout/HLayout.js~HLayout.create",
    "method"
  ],
  [
    "nawi/widgets/layout/hlayout/hlayoutproto.js",
    "file/nawi/widgets/layout/hlayout/HLayoutProto.js.html",
    "nawi/widgets/layout/hlayout/HLayoutProto.js",
    "file"
  ],
  [
    "nawi/widgets/layout/hlayout/hlayoutproto.js~hlayoutproto#createdcallback",
    "class/nawi/widgets/layout/hlayout/HLayoutProto.js~HLayoutProto.html#instance-method-createdCallback",
    "nawi/widgets/layout/hlayout/HLayoutProto.js~HLayoutProto#createdCallback",
    "method"
  ],
  [
    "nawi/widgets/layout/hlayout/hlayoutproto.js~hlayoutproto#xstyle",
    "class/nawi/widgets/layout/hlayout/HLayoutProto.js~HLayoutProto.html#instance-member-xstyle",
    "nawi/widgets/layout/hlayout/HLayoutProto.js~HLayoutProto#xstyle",
    "member"
  ],
  [
    "nawi/widgets/layout/hlayout/hlayoutstyle.js",
    "file/nawi/widgets/layout/hlayout/HLayoutStyle.js.html",
    "nawi/widgets/layout/hlayout/HLayoutStyle.js",
    "file"
  ],
  [
    "nawi/widgets/view/tabview/tabview.js",
    "file/nawi/widgets/view/tabview/TabView.js.html",
    "nawi/widgets/view/tabview/TabView.js",
    "file"
  ],
  [
    "nawi/widgets/view/tabview/tabview.js~tabview#constructor",
    "class/nawi/widgets/view/tabview/TabView.js~TabView.html#instance-constructor-constructor",
    "nawi/widgets/view/tabview/TabView.js~TabView#constructor",
    "method"
  ],
  [
    "nawi/widgets/view/tabview/tabview.js~tabview.create",
    "class/nawi/widgets/view/tabview/TabView.js~TabView.html#static-method-create",
    "nawi/widgets/view/tabview/TabView.js~TabView.create",
    "method"
  ],
  [
    "nawi/widgets/view/tabview/tabviewproto.js",
    "file/nawi/widgets/view/tabview/TabViewProto.js.html",
    "nawi/widgets/view/tabview/TabViewProto.js",
    "file"
  ],
  [
    "nawi/widgets/view/tabview/tabviewproto.js~tabviewproto#createdcallback",
    "class/nawi/widgets/view/tabview/TabViewProto.js~TabViewProto.html#instance-method-createdCallback",
    "nawi/widgets/view/tabview/TabViewProto.js~TabViewProto#createdCallback",
    "method"
  ],
  [
    "nawi/widgets/view/tabview/tabviewproto.js~tabviewproto#xstyle",
    "class/nawi/widgets/view/tabview/TabViewProto.js~TabViewProto.html#instance-member-xstyle",
    "nawi/widgets/view/tabview/TabViewProto.js~TabViewProto#xstyle",
    "member"
  ],
  [
    "nawi/widgets/view/tabview/tabviewstyle.js",
    "file/nawi/widgets/view/tabview/TabViewStyle.js.html",
    "nawi/widgets/view/tabview/TabViewStyle.js",
    "file"
  ],
  [
    "nawi/widgets/view/tabview/tabviewstyle.js~tabviewstyle#constructor",
    "class/nawi/widgets/view/tabview/TabViewStyle.js~TabViewStyle.html#instance-constructor-constructor",
    "nawi/widgets/view/tabview/TabViewStyle.js~TabViewStyle#constructor",
    "method"
  ],
  [
    "nawi/widgets/widget/stylecontainer.js",
    "file/nawi/widgets/widget/StyleContainer.js.html",
    "nawi/widgets/widget/StyleContainer.js",
    "file"
  ],
  [
    "nawi/widgets/widget/stylecontainer.js~stylecontainer#constructor",
    "class/nawi/widgets/widget/StyleContainer.js~StyleContainer.html#instance-constructor-constructor",
    "nawi/widgets/widget/StyleContainer.js~StyleContainer#constructor",
    "method"
  ],
  [
    "nawi/widgets/widget/stylecontainer.js~stylecontainer#generatecontainers",
    "class/nawi/widgets/widget/StyleContainer.js~StyleContainer.html#instance-method-generateContainers",
    "nawi/widgets/widget/StyleContainer.js~StyleContainer#generateContainers",
    "method"
  ],
  [
    "nawi/widgets/widget/widget.js",
    "file/nawi/widgets/widget/Widget.js.html",
    "nawi/widgets/widget/Widget.js",
    "file"
  ],
  [
    "nawi/widgets/widget/widget.js~widget#constructor",
    "class/nawi/widgets/widget/Widget.js~Widget.html#instance-constructor-constructor",
    "nawi/widgets/widget/Widget.js~Widget#constructor",
    "method"
  ],
  [
    "nawi/widgets/widget/widget.js~widget.factory",
    "class/nawi/widgets/widget/Widget.js~Widget.html#static-method-factory",
    "nawi/widgets/widget/Widget.js~Widget.factory",
    "method"
  ],
  [
    "nawi/widgets/widget/widgetproto.js",
    "file/nawi/widgets/widget/WidgetProto.js.html",
    "nawi/widgets/widget/WidgetProto.js",
    "file"
  ],
  [
    "nawi/widgets/widget/widgetstyle.js",
    "file/nawi/widgets/widget/WidgetStyle.js.html",
    "nawi/widgets/widget/WidgetStyle.js",
    "file"
  ],
  [
    "nawi/widgets/widget/widgetstyle.js~widgetstyle#constructor",
    "class/nawi/widgets/widget/WidgetStyle.js~WidgetStyle.html#instance-constructor-constructor",
    "nawi/widgets/widget/WidgetStyle.js~WidgetStyle#constructor",
    "method"
  ]
]